# Generated by Django 5.1.6 on 2025-04-02 18:14

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tenant',
            managers=[
                ('objects', account.models.TenantUserManager()),
            ],
        ),
    ]
