# Generated by Django 5.1.6 on 2025-04-02 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('no_of_units', models.IntegerField(blank=True, null=True)),
                ('cost_of_rent', models.IntegerField(blank=True, null=True)),
                ('availability', models.IntegerField()),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='properties_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tenancy_Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start_date', models.DateField()),
                ('contract_duration', models.IntegerField(help_text='Duration in months')),
                ('contact_end_date', models.DateField(blank=True, null=True)),
                ('total_amount_paid', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancy_agreements', to='account.tenant')),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancy_agreements', to='rent_in_app.property')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('amount_left', models.IntegerField(blank=True, null=True)),
                ('total_amount_paid', models.IntegerField(blank=True, null=True)),
                ('first_payment_date', models.DateField(auto_now=True)),
                ('last_payment_date', models.DateField(auto_now_add=True)),
                ('phone_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='account.tenant')),
                ('tenancy_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rent_in_app.tenancy_agreement')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=14, unique=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('max_No_of_people', models.IntegerField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='rent_in_app.property')),
            ],
        ),
        migrations.AddField(
            model_name='tenancy_agreement',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancy_agreements', to='rent_in_app.unit'),
        ),
    ]
