# Generated by Django 5.1.7 on 2025-04-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_in_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='room_number',
        ),
    ]
