# Generated by Django 5.1.7 on 2025-04-01 23:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_in_app', '0002_remove_unit_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='room_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
